pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'Kali:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'dockeLogin'
- script: docker push $(dockerId)/$(imageName)
  displayName: 'dockerHub'